# Generated by Django 4.1.6 on 2023-02-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=30, verbose_name='Fabricante')),
            ],
            options={
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de veículo')),
            ],
            options={
                'verbose_name_plural': 'Tipos de veículos',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('motor', models.CharField(max_length=30, verbose_name='Motor')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
                ('ano', models.IntegerField(default=2022, verbose_name='Ano')),
                ('placa', models.CharField(max_length=12, verbose_name='Placa')),
                ('km', models.IntegerField(blank=True, default=0, null=True, verbose_name='KM')),
                ('cambio', models.CharField(max_length=30, verbose_name='Câmbio')),
                ('combustivel', models.CharField(max_length=30, verbose_name='Combustível')),
                ('portas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Portas')),
                ('opcionais', models.TextField(blank=True, null=True, verbose_name='Opcionais')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preco')),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('V', 'Vendido')], default=('V', 'Vendido'), max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Modelo')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.fabricante', verbose_name='Fabricante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo', verbose_name='Tipo de Veículo')),
            ],
            options={
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='VeiculoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_veiculos', verbose_name='Fotos do veículo')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipo', verbose_name='Tipo de Veículo'),
        ),
    ]
