# Generated by Django 4.1.6 on 2023-02-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_vizualizacoes_alter_veiculo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='estado',
            field=models.CharField(choices=[('N', 'Novo'), ('S', 'Seminovo'), ('U', 'Usado')], default=('U', 'Usado'), max_length=1),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria', verbose_name='Categoria'),
        ),
    ]
