# Generated by Django 4.1.6 on 2023-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='vizualizacoes',
            field=models.IntegerField(default=0, verbose_name='Vizualizações'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('V', 'Vendido')], default=('D', 'Disponível'), max_length=1),
        ),
    ]
